### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by donmccurdy** [donmccurdy/three-pathfinding#2]
- [x] Remove dependency on Underscore (in favor of ES5)
- [x] Remove dependency on ProgressBar
- [x] Support CommonJS in the browser (see #6)
- [x] Expose a little more API surface for the nav mesh* 
- [x] Allow logs to be disabled

*e.g. so that users of the library can inspect the current node (and perhaps get the color of the face, to interpret for gameplay?)
